#!/bin/bash
SQUEAK_VERSION=$1
VM_VERSION=$2
VM_DATE=$3
IMAGE_FILE=Squeak.image
./getVms $VM_VERSION $VM_DATE
./extractVms
./increaseBuildNumber
./editSqueakIni $SQUEAK_VERSION $IMAGE_FILE
./editInfoPlist $SQUEAK_VERSION $VM_VERSION
./renameToSqueak
./removeConsoleFromWindows
cp cogwin/* Cog.app/
mkdir Cog.app/Contents/Linux-i686
cp -r coglinux/bin Cog.app/Contents/Linux-i686/
cp -r coglinux/lib Cog.app/Contents/Linux-i686/
cp squeak.sh Cog.app/
cp Squeak.ini Cog.app/
cp splash.bmp Cog.app/
cp Info.plist Cog.app/Contents/
cp *.icns Cog.app/Contents/Resources/
#./getImage
./copyImage
./makeZipFile $SQUEAK_VERSION
./cleanUp
echo "*********************************************"
echo "before running this you should have put an image, changes and sources file in this directory.  Hopefully you did.  If not you'll  have to get the image, sources, and changes file and rename them to ${IMAGE_FILE} and put them in Contents/Resources/"
echo "*********************************************"
