#!/bin/bash
SQUEAK_VERSION=$1
VM_VERSION=$2
IDENTIFIER=${SQUEAK_VERSION//./}
touch editSqueakShSed
echo "s/4\.4/${SQUEAK_VERSION}/" >> editSqueakShSed
echo "s/2697/${VM_VERSION}/" >> editSqueakShSed
echo "s/44/${IDENTIFIER}/" >> editSqueakShSed
sed -f editSqueakShSed < Info.plist.orig >Info.plist
rm editSqueakShSed
