#!/bin/bash
# Eliot Miranda is using a version number as the directory name .e.g 2749 and a year/week number e.g. 13.28 and this script expects them passed in in that order.
VM_DIRECTORY_NUMBER=$1
VM_DATE_NUMBER=$2
VM_DOWNLOAD_NUMBER=-$VM_DATE_NUMBER.$VM_DIRECTORY_NUMBER
wget http://www.mirandabanda.org/files/Cog/VM/VM.r$VM_DIRECTORY_NUMBER/cogwin$VM_DOWNLOAD_NUMBER.zip
wget http://www.mirandabanda.org/files/Cog/VM/VM.r$VM_DIRECTORY_NUMBER/coglinux$VM_DOWNLOAD_NUMBER.tgz
wget http://www.mirandabanda.org/files/Cog/VM/VM.r$VM_DIRECTORY_NUMBER/Cog.app$VM_DOWNLOAD_NUMBER.tgz
